cookbook_django/recipebookproject/recipebookapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views
from recipebookproject import settings

app_name = "recipebookapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('user/', views.user, name='user'),
    path('logout/', views.user_logout, name='logout'),
    path('cooker/', views.cooker, name='cooker'),
    path('recipe_add/', views.recipe_add, name='recipe_add'),
    path('recipe_edit/<int:recipe_id>/', views.recipe_edit, name='recipe_edit'),
    path('recipe_detail/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe_delete/<int:recipe_id>/', views.recipe_delete, name='recipe_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.handler404
handler500 = views.handler500

cookbook_django/recipebookproject/recipebookproject/urls.py
from django.contrib import admin
from django.urls import path, include

# Основные URL
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipebookapp.urls', namespace='recipebookapp')),
]

cookbook_django/recipebookproject/recipebookapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import CheckConstraint, Q
from django.db.models.functions import Lower


class CustomUser(AbstractUser):
    USERNAME_FIELD = 'email'  # переопределение поля идентификации
    REQUIRED_FIELDS = ["username"]
    email = models.EmailField(unique=True)

    class Meta:
        constraints = [
            CheckConstraint(check=Q(email=Lower("email")), name="user_email_lower"),
        ]


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    cooking_steps = models.TextField()
    cooking_time = models.TimeField()
    image = models.ImageField(null=True, upload_to='recipes/', blank=True)
    entry_date = models.DateTimeField(auto_now_add=True)
    is_visible = models.BooleanField(default=True)
    author = models.ForeignKey('CustomUser', on_delete=models.SET_NULL, null=True)
    meal_type = models.CharField(
        max_length=20,
        default='snack',
        verbose_name='Тип приема пищи'
    )

cookbook_django/recipebookproject/recipebookapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from recipebookapp.models import CustomUser, Recipe


class RecipeForm(forms.ModelForm):
    title = forms.CharField(max_length=100,
                            label="Наименование блюда",
                            widget=forms.TextInput(attrs={'class': 'recipe-form__title'}))
    description = forms.CharField(max_length=250,
                                  label="Краткое описание блюда",
                                  widget=forms.Textarea(attrs={'class': 'recipe-form__description'}))
    cooking_steps = forms.CharField(max_length=10000,
                                    label="Шаги приготовления",
                                    widget=forms.Textarea(attrs={'class': 'recipe-form__cooking'}))
    cooking_time = forms.TimeField(label="Время приготовления",
                                   help_text='Укажите время приготовления',
                                   widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'}))
    image = forms.ImageField(required=False, label="Изображение блюда")
    class Meta:
        model = Recipe
        fields = ('title', 'description', 'cooking_steps', 'cooking_time', 'image', 'meal_type')
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['meal_type'] = forms.ChoiceField(
            choices=[
                ('breakfast', 'Завтрак'),
                ('snack', 'Перекус'),
                ('lunch', 'Обед'),
                ('dinner', 'Ужин'),
            ],
            label="Тип приема пищи",
            widget=forms.Select(attrs={'class': 'form-control'})
        )



class SignInForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'placeholder': 'Пароль'}),
    )


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Имя'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Пароль'
        self.fields['password1'].widget.attrs[
            'title'] = 'Минимум 8 символов. По одному из: заглавная и строчная буква, цифра и спецсимвол.'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Такой email уже используется в системе')
        return email
class SearchForm(forms.Form):
    search = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'search-input',
            'placeholder': 'Поиск рецептов...'
        })
    )

cookbook_django/recipebookproject/recipebookapp/views.py
from random import randint
from .forms import SearchForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import logging

from .forms import SignInForm, SignUpForm, RecipeForm
from .models import Recipe

logger = logging.getLogger(__name__)


def log_this(f):
    def wrapper(*args, **kwargs):
        res = f(*args, **kwargs)
        logger.info(f'Func "{f.__name__}" was called')
        return res

    return wrapper


def get_random_recipe():
    count = Recipe.objects.filter(is_visible=True).count()
    random_index = randint(0, count - 1)
    random_recipe = Recipe.objects.all()[random_index]
    return random_recipe


@log_this
def index(request):
    number_of_cards = 5
    recipes = []
    count = Recipe.objects.filter(is_visible=True).count()
    if count == 0:
        return render(request, "recipebookapp/index.html")
    if count == 1:
        recipes = [Recipe.objects.all()[0]]
        return render(request, "recipebookapp/index.html", {'recipes': recipes})
    if 1 < count < number_of_cards:
        number_of_cards = count
    while len(recipes) < number_of_cards:
        recipe = get_random_recipe()
        if recipe not in recipes:
            recipes.append(recipe)
    return render(request, "recipebookapp/index.html", {'recipes': recipes})


@log_this
def user(request):
    if request.method == 'POST':
        if 'register' in request.POST:
            reg_form = SignUpForm(request.POST)
            if reg_form.is_valid():
                reg_form.save()
                email = reg_form.cleaned_data['email']
                password = reg_form.cleaned_data['password1']
                user = authenticate(request, email=email, password=password)
                login(request, user)
                return redirect('/cooker')
            else:
                messages.error(request, 'Форма регистрации заполнена неверно')
        elif 'login' in request.POST:
            login_form = SignInForm(request.POST)
            if login_form.is_valid():
                if user := authenticate(request, **login_form.cleaned_data):
                    login(request, user)
                    return redirect('/cooker')
                messages.error(request, 'Ошибка авторизации')
            else:
                messages.error(request, 'Форма авторизации заполнена неверно')

    reg_form = SignUpForm()
    login_form = SignInForm()

    context = {
        'reg_form': reg_form,
        'login_form': login_form
    }
    return render(request, 'recipebookapp/user.html', context)


@log_this
@login_required
def user_logout(request):
    logout(request)
    return redirect('/')


@log_this
@login_required
def cooker(request):
    recipes = Recipe.objects.filter(is_visible=True, author=request.user)
    return render(request, "recipebookapp/cooker.html", {'recipes': recipes})


@log_this
@login_required
def recipe_add(request):
    is_completed = False
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            cooking_steps = form.cleaned_data['cooking_steps']
            cooking_time = form.cleaned_data['cooking_time']
            image = form.cleaned_data['image']
            author = request.user
            meal_type = form.cleaned_data['meal_type']
            recipe = Recipe(
                title=title,
                description=description,
                cooking_steps=cooking_steps,
                cooking_time=cooking_time,
                image=image,
                author=author,
                meal_type=meal_type
            )

            recipe.save()
            is_completed = True
    else:
        is_completed = False
        form = RecipeForm()
    return render(request, 'recipebookapp/recipe_add.html',
                  {'form': form, 'is_completed': is_completed})


@log_this
@login_required
def recipe_edit(request, recipe_id):
    is_completed = False
    recipe = Recipe.objects.filter(pk=recipe_id).first()
    recipe_img = recipe.image
    if request.user != recipe.author:
        return redirect('/')
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe.title = form.cleaned_data['title']
            recipe.description = form.cleaned_data['description']
            recipe.cooking_steps = form.cleaned_data['cooking_steps']
            recipe.cooking_time = form.cleaned_data['cooking_time']
            recipe.meal_type = form.cleaned_data['meal_type']
            if form.cleaned_data['image'] is not None:
                recipe.image = form.cleaned_data['image']
            recipe.save()

            is_completed = True
    else:
        is_completed = False
        if recipe:
            data = {'title': recipe.title,
                    'description': recipe.description,
                    'cooking_steps': recipe.cooking_steps,
                    'cooking_time': recipe.cooking_time,
                    'meal_type': recipe.meal_type}
            if recipe.image is not None:
                recipe_img = recipe.image
            form = RecipeForm(data)

        else:
            form = RecipeForm()
    return render(request, 'recipebookapp/recipe_edit.html',
                  {'form': form,
                   'is_completed': is_completed,
                   'recipe_img': recipe_img,
                   'recipe': recipe})


@log_this
@login_required
def recipe_delete(request, recipe_id):
    recipe = Recipe.objects.filter(pk=recipe_id).first()
    if request.user != recipe.author:
        return redirect('/')
    if recipe:
        recipe.is_visible = False
        recipe.save()
    return redirect('/cooker')


@log_this
def recipe_detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    context = {
        'recipe': recipe
    }
    return render(request, 'recipebookapp/recipe_detail.html', context)


@log_this
def handler404(request, exception):
    return render(request, '404.html', status=404)


@log_this
def handler500(request):
    return render(request, '500.html', status=500)

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/cooker.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_box.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_detail.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов - личный кабинет
{% endblock %}

{% block header %}
Личный кабинет
{% endblock %}

{% block user %}

{% if user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/logout/" data-title="Покинуть кухню"><img style="width: 35px;"
                                                                                 src="{% static 'img/logout_icon.png' %}"></a>
</li>
{% endif %}

{% endblock %}

{% block content %}
    <div class="recipes_hello">
<p>Добро пожаловать в Ваш личный кабинет на сайте рецептов!</p>
<p>Здесь вы можете сохранять и изменять свои рецепты.
    Надеемся, что наш сайт станет вашим надежным помощником в кулинарии!</p>

<a class="recipe_btn" href="/recipe_add/">Новый рецепт</a>
    </div>
<div class="recipes_container">
    {% if recipes %}
        {% for recipe in recipes %}
            <div class="recipe_box">
                <div class="recipe_box__image">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}" alt="">
                    {% else %}
                        <img src="{% static 'img/default_recipe_img.jpg' %}" alt="">
                    {% endif %}
                </div>
                <div class="recipe_box__text">
                    <h3>{{ recipe.title }}</h3>
                    <p>{{ recipe.description }}</p>
                    <a href="/recipe_detail/{{ recipe.id }}">Подробнее</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>



{% endblock %}

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_box.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов
{% endblock %}

{% block header %}
Сайт рецептов
{% endblock %}

{% block user %}

{% if not user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/user/" data-title="Доступ на кухню"><img style="width: 35px;"
                                                                               src="{% static 'img/cooker.png' %}"></a>
</li>
{% endif %}

{% if user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/cooker/" data-title="Доступ на кухню"><img style="width: 35px;"
                                                                               src="{% static 'img/cooker.png' %}"></a>
</li>
<li>
    <a class="main_menu__link" href="/logout/" data-title="Покинуть кухню"><img style="width: 35px;"
                                                                                 src="{% static 'img/logout_icon.png' %}"></a>
</li>
{% endif %}


{% endblock %}

{% block content %}
<div class="welcome_text">
    <h1>Добро пожаловать на наш сайт рецептов!</h1>
    <p>
        Мы рады приветствовать вас в мире кулинарного вдохновения! Наш сайт создан специально для тех, кто ищет
        новые вкусы, оригинальные идеи и проверенные рецепты на любой случай.
    </p>
    <ul>
        <li><strong>Рецепты на любой вкус:</strong> от простых домашних блюд до изысканных ресторанных шедевров.</li>
        <li><strong>Идеи для каждого повода:</strong> будь то семейный ужин, праздничный стол или быстрый перекус.</li>
        <li><strong>Разнообразие категорий:</strong> первые и вторые блюда, аппетитные закуски, свежие салаты, сладкие десерты и многое другое.</li>
    </ul>
    <p>
        Каждый рецепт на нашем сайте — это шаг к созданию кулинарного произведения искусства. Мы стремимся вдохновлять
        вас на эксперименты и помогать вам удивлять близких вкусными блюдами.
    </p>
    <p class="call_to_action">
        <strong>Начните своё путешествие по каталогу рецептов прямо сейчас!</strong>
    </p>
    <p>
        Мы уверены, что вы найдёте именно то, что искали. Пусть процесс приготовления будет лёгким, а результат —
        восхитительным.
    </p>
    <p><em>Приятного аппетита и удачных экспериментов на вашей кухне!</em></p>
</div>


<div class="recipes_container">
    {% if recipes %}
        {% for recipe in recipes %}
            <div class="recipe_box">
                <div class="recipe_box__image">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}" alt="">
                    {% else %}
                        <img src="{% static 'img/default_recipe_img.jpg' %}" alt="">
                    {% endif %}
                </div>
                <div class="recipe_box__text">
                    <h3>{{ recipe.title }}</h3>
                    <p>{{ recipe.description }}</p>
                    <a href="/recipe_detail/{{ recipe.id }}">Подробнее</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/recipe_add.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_form.css' %}">
<link rel="stylesheet" href="{% static 'css/popup.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов - новый рецепт
{% endblock %}

{% block my_script %}
<script type="text/javascript" src="{% static 'js/textFieldCounter.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/popup.js' %}" defer></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block user %}
{% if user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/cooker/" data-title="Доступ на кухню">
        <img style="width: 35px;" src="{% static 'img/cooker.png' %}">
    </a>
</li>
<li>
    <a class="main_menu__link" href="/logout/" data-title="Покинуть кухню">
        <img style="width: 35px;" src="{% static 'img/logout_icon.png' %}">
    </a>
</li>
{% endif %}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form_block">
        {{ form.title.label }}
        {{ form.title }}
        <div class="title-field__counter"></div>
    </div>
    <div class="form_block">
        {{ form.description.label }}
        {{ form.description }}
        <div class="description-field__counter"></div>
    </div>
    <div class="form_block">
        {{ form.cooking_steps.label }}
        {{ form.cooking_steps }}
        <div class="cooking_steps-field__counter"></div>
    </div>
    <div class="form_block last_block">
        <div class="form_block item_center">
            {{ form.cooking_time.label }}
            {{ form.cooking_time }}
        </div>
        <div class="form_block item_center">
            {{ form.image.label }}
            {{ form.image }}
        </div>
        <div class="form_block item_center">
            {{ form.meal_type.label_tag }}
            {{ form.meal_type }}
            {% if form.meal_type.errors %}
                <div class="error">{{ form.meal_type.errors }}</div>
            {% endif %}
        </div>
        
    </div>
    <div class="buttons_block_row">
        <button class="btn open-popUp" type="submit">Сохранить рецепт</button>
        <a href='/cooker/' class="btn">Отмена</a>
    </div>
</form>
{% if is_completed == True %}
<div class="popUp show-popUp">
    <div class="popUp-content">
        <p>Новый рецепт успешно сохранен</p>
        <button class="btn close-popUp">ОК</button>
    </div>
</div>
{% endif %}
{% endblock %}

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/recipe_detail.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_detail.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов - {{ recipe.title }}
{% endblock %}

{% block header %}
{{ recipe.title }}
{% endblock %}

{% block user %}

{% if not user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/user/" data-title="Вход в профиль"><img style="width: 35px;"
                                                                               src="{% static 'img/cooker.png' %}"></a>
</li>
{% endif %}

{% if user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/cooker/" data-title="Вход в профиль"><img style="width: 35px;"
                                                                                 src="{% static 'img/cooker.png' %}"></a>
</li>
<li>
    <a class="main_menu__link" href="/logout/" data-title="Покинуть профиль"><img style="width: 35px;"
                                                                                src="{% static 'img/logout_icon.png' %}"></a>
</li>
{% endif %}


{% endblock %}

{% block content %}
<div class="recipe_common">
    <div class="recipe_container">
        <div class="recipe_left">
            <div class="recipe_image">
                {% if recipe.image %}
                <img src="{{ recipe.image.url }}" alt="">
                {% else %}
                <img src="{% static 'img/default_recipe_img.jpg' %}" alt="">
                {% endif %}
            </div>
        </div>
        <div class="recipe_right">
            <div class="recipe_cooking">{{ recipe.cooking_steps }}</div>
            <div class="recipe_info">
                <p>Время приготовления: {{ recipe.cooking_time }}</p>
                {% if recipe.category %}
                <p>Тип блюда: {{ recipe.category }}</p>
                {% endif %}
                {% if recipe.meal_type %}
                <p>Тип блюда: {{ recipe.get_meal_type_display }}</p>
                {% endif %}
                {% if recipe.author %}
                <div class="recipe_author">Автор: {{ recipe.author }}</div>
                {% endif %}

            </div>
            <div class="recipe_buttons">
                {% if user == recipe.author %}
                <a class="recipe_btn" href="/recipe_edit/{{ recipe.id }}">Изменить</a>
                <a class="recipe_btn" href="/recipe_delete/{{ recipe.id }}">Удалить</a>
                {% endif %}
                <a class="recipe_btn" href="/">Назад</a>
            </div>
        </div>

    </div>
</div>
{% endblock %}

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/recipe_edit.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/recipe_form.css' %}">
<link rel="stylesheet" href="{% static 'css/popup.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов - новый рецепт
{% endblock %}

{% block my_script %}
<script type="text/javascript" src="{% static 'js/popup.js' %}" defer></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block user %}
{% if user.is_authenticated %}
<li>
    <a class="main_menu__link" href="/cooker/" data-title="Доступ на кухню">
        <img style="width: 35px;" src="{% static 'img/cooker.png' %}">
    </a>
</li>
<li>
    <a class="main_menu__link" href="/logout/" data-title="Покинуть кухню">
        <img style="width: 35px;" src="{% static 'img/logout_icon.png' %}">
    </a>
</li>
{% endif %}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form_block">
        {{ form.title.label }}
        {{ form.title }}
        <div class="title-field__counter"></div>
    </div>
    <div class="form_block">
        {{ form.description.label }}
        {{ form.description }}
        <div class="description-field__counter"></div>
    </div>
    <div class="form_block">
        {{ form.cooking_steps.label }}
        {{ form.cooking_steps }}
        <div class="cooking_steps-field__counter"></div>
    </div>
    <div class="form_block last_block">
        <div class="form_block item_center">
            {{ form.cooking_time.label }}
            {{ form.cooking_time }}
        </div>
        <div class="form_block item_center">
            {{ form.image.label }}
            {% if recipe_img.url != null %}
                <img src="{{ recipe_img.url }}" width="100px" alt="">
            {% else %}
                <p>На данный момент нет изображения</p>
            {% endif %}
            {{ form.image }}
        </div>
    </div>
    <div class="form_block item_center">
        {{ form.meal_type.label }}
        {{ form.meal_type }}
    </div>
    <div class="buttons_block_row">
        <button class="btn open-popUp" type="submit">Сохранить изменения</button>
        <a href='/cooker/' class="btn">Отмена</a>
    </div>
</form>
{% if is_completed == True %}
<div class="popUp show-popUp">
    <div class="popUp-content">
        <p>Рецепт успешно изменен</p>
        <button class="btn close-popUp">ОК</button>
    </div>
</div>
{% endif %}
{% endblock %}

cookbook_django/recipebookproject/recipebookapp/templates/recipebookapp/user.html
{% extends 'base.html' %}
{% load static %}

{% block my_style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block title %}
Сайт рецептов - пользователь
{% endblock %}

{% block my_script %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous">
<script type="text/javascript" src="{% static 'js/user.js' %}" defer></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}

<div class="container" id="container">
    <div class="form-container sign-up-container">
        <form method="post">
            {% csrf_token %}
            <h1>Регистрация</h1>
            {{ reg_form.username }}
            {{ reg_form.email }}
            {{ reg_form.password1 }}
            {{ reg_form.password2 }}
            <button type="submit" name="register">Зарегистрироваться</button>
            {% if messages %}
                {% for message in messages %}
                    <p class="user_form_error">{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
    <div class="form-container sign-in-container">
        <form method="post">
            {% csrf_token %}
            <h1>Авторизация</h1>
            {{ login_form.email }}
            {{ login_form.password }}
            <button type="submit" name="login">Войти</button>
            {% if messages %}
                {% for message in messages %}
                    <p class="user_form_error">{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1>С возвращением!</h1>
                <p>Пожалуйста, войдите в систему</p>
                <button class="ghost" id="signIn">Авторизоваться</button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>Добро пожаловать, дорогой гость!</h1>
                <p>Зарегистрируйтесь для продолжения </p>
                <button class="ghost" id="signUp">Зарегистрироваться</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}